version: '3'

services:
  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    environment:
      DATABASE_URL: mongodb://root:root@db:27017/nest?authSource=admin&connectTimeoutMS=5000
    depends_on:
      - db

  db:
    image: bitnami/mongodb:5.0.17
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: nest

volumes:
  mongodb_data:
    driver: local